POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jollipop",
    "number": "23423323"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Rebekah",
    "number": "7852749"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Joshua",
    "number": "35304832"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Amamama",
    "number": "6384903"
}