POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Zacky",
    "number": "638432903"
}

###

PUT http://localhost:3001/api/persons/5fbf54a1446ddd567ff4e174
Content-Type: application/json

{
    "name": "Zacky",
    "number": "43832344323",
    "id": "5fbf54a1446ddd567ff4e174"
}